$engine: 3
$onesync: on
name: FXServer CFX Default FiveM
description: Recipe for the base resources required to run a minimal FXServer FiveM server.

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

    # Download server.cfg
  - action: download_github
    src: https://github.com/nikgkikas12/FXServer-FiveM
    ref: main
    dest: ./tmp/fx

  - action: move_path
    src: ./tmp/fx/server.cfg
    dest: ./server.cfg

 - action: remove_path
    path: ./tmp
